-- Creating KSI table 

CREATE TABLE Motor_Vehicle_Collisions     ( _id int,
                        ACCNUM varchar(100),
                        "YEAR" int,
                        "DATE" DATE,
                        "TIME" int,
                        "STREET1" varchar(100),
                        "STREET2" varchar(100),
                        "OFFSET" varchar(100),
                        "ROAD_CLASS" varchar(100),
                        "DISTRICT" varchar(100),
                        "WARDNUM" varchar(100),-- Have blanks, So changed the datatype to varchar
                        "LOCCOORD" varchar(100),
                        "ACCLOC" varchar(100),
                        "TRAFFCTL" varchar(100),
					    "VISIBILITY" varchar(100),
					    "LIGHT" varchar(100), 
					    "RDSFCOND" varchar(100),
					    "ACCLASS" varchar(100),
					    "IMPACTYPE" varchar(100),
					    "INVTYPE" varchar(100),
					    "INVAGE" varchar(100),
					    "INJURY" varchar(100),
					    "FATAL_NO" varchar(100),
					   	"INITDIR" varchar(100),
					    "VEHTYPE" varchar(100),
					    "MANOEUVER" varchar(100),
					    "DRIVACT" varchar(100),
					    "DRIVCOND" varchar(100),
					    "PEDTYPE" varchar(100),
					    "PEDACT" varchar(100),
					    "PEDCOND" varchar(100),
					    "CYCLISTYPE" varchar(100),
					    "CYCACT" varchar(100),
					    "CYCCOND" varchar(100),
					    "PEDESTRIAN" varchar(100),
					    "CYCLIST" varchar(100),
					    "AUTOMOBILE" varchar(100),
					    "MOTORCYCLE" varchar(100),
					    "TRUCK" varchar(100),
					    "TRSN_CITY_VEH" varchar(100),
					    "EMERG_VEH" varchar(100),
					    "PASSENGER" varchar(100),
					   "SPEEDING" varchar(100),
					    "AG_DRIV" varchar(100),
					    "REDLIGHT" varchar(100),
					    "ALCOHOL" varchar(100),
					    "DISABILITY" varchar(100),
					    "HOOD_158" varchar(100),
					    "NEIGHBOURHOOD_158" varchar(100),
					    "HOOD_140" varchar(100),
					    "NEIGHBOURHOOD_140" varchar(100),
					    "DIVISION" varchar(100),
					    "geometry" varchar(100));
						
								
						
-- Dropping columns

ALTER TABLE Motor_Vehicle_Collisions
DROP COLUMN _id,
DROP COLUMN ACCNUM,
DROP COLUMN "YEAR",
DROP COLUMN "DATE",
DROP COLUMN "WARDNUM",
DROP COLUMN "STREET1",
DROP COLUMN "STREET2",
DROP COLUMN "DISTRICT",
DROP COLUMN "NEIGHBOURHOOD_158",
DROP COLUMN "NEIGHBOURHOOD_140",
DROP COLUMN "DIVISION",
DROP COLUMN "geometry",
DROP COLUMN "FATAL_NO",
DROP COLUMN "PEDTYPE",
DROP COLUMN "PEDACT",
DROP COLUMN "PEDCOND",
DROP COLUMN "CYCLISTYPE",
DROP COLUMN "CYCACT",
DROP COLUMN "CYCCOND",
DROP COLUMN "TIME",
DROP COLUMN "OFFSET",
DROP COLUMN "HOOD_158",
DROP COLUMN "HOOD_140";


-- Displaying data from table 

SELECT * FROM Motor_Vehicle_Collisions	